Also add dummy Wine64
rahatarmanahmed/electron-packager-dummy-wine pull request #3
Opened 2020-10-01 16:30 UTC by davidsharp

Newer versions of `electron-packager` require wine64, since the intention of this library is to dummy out the need for wine, this should be dummied out too

2020-10-03 00:31 UTC, rahatarmanahmed requested changes
Can you revert the version bump? I'll take care of that myself.

2020-10-03 00:32 UTC, rahatarmanahmed commented
This is great, thanks!

2020-10-05 08:09 UTC, davidsharp commented
Done 👍

2020-10-09 01:43 UTC, rahatarmanahmed approved these changes

2020-10-09 01:43 UTC, merged

2020-10-09 01:45 UTC, rahatarmanahmed commented
Published in v1.1.0. Thanks!